var MITCHELLSTARC = 56;
var GLENNMCGRATH = 11;
var BRETTLEE = 58;
var add = MITCHELLSTARC + GLENNMCGRATH + BRETTLEE;
console.log(add);

var MITCHELLSTARC1 = 156;
var GLENNMCGRATH1 = 11;
var BRETTLEE1 = 58;
var subtract = MITCHELLSTARC1 - GLENNMCGRATH1 - BRETTLEE1;
console.log(subtract);

var MITCHELLSTARC2 = 56;
var GLENNMCGRATH2 = 11;
var BRETTLEE2 = 58;
var multiply = MITCHELLSTARC2 * GLENNMCGRATH2 * BRETTLEE2;
console.log(multiply);

var MITCHELLSTARC3 = 55;
var BRETTLEE3 = 11;
var divide = MITCHELLSTARC3 / BRETTLEE3;
console.log(divide);

var MITCHELLSTARC4 = 4;
var GLENNMCGRATH4 = 3;
var BRETTLEE4 = 4;
var PATCUMMINS4 = 2;
var SIMPLIFY = ((MITCHELLSTARC4 + BRETTLEE4) - PATCUMMINS4) / GLENNMCGRATH4;
console.log(SIMPLIFY);